### ISSUE TITLE
Error on creating invoice

### ISSUE THREAD

**Issue by tonybranfort** [tonybranfort/immidb#55]
Invoice is not created for a client when Invoice button is clicked; user is given error.  Logging error shows "ERROR (public,api). Timeout wating for invoice page; max loops."

**Comment by tonybranfort** [comment]
I got the same error when going to a different client and creating an invoice.  Another user confirmed also getting error.  Looking at the log tho, has only happened those 3 times today (1st user reporting, me, 2nd user to check).  I was able to create the invoice when trying again.  Appears to be intermittent.

**Comment by tonybranfort** [comment]
Server log: 
```
info: Error: undefined is not a function (evaluating 'e.endsWith("/")')
info: v@http://localhost:xxxxx/build/app.min.js:2:22355
info: http://localhost:xxxxx/build/app.min.js:2:23715
info: http://localhost:xxxxx/components/bower_components/angular/angular.min.js:111:183
info: $eval@http://localhost:xxxxx/components/bower_components/angular/angular.min.js:125:40
info: $digest@http://localhost:xxxxx/components/bower_components/angular/angular.min.js:122:132
info: $apply@http://localhost:xxxxx/components/bower_components/angular/angular.min.js:125:314
info: m@http://localhost:xxxxx/components/bower_components/angular/angular.min.js:80:461
info: N@http://localhost:xxxxx/components/bower_components/angular/angular.min.js:85:33
info: onload@http://localhost:xxxxx/components/bower_components/angular/angular.min.js:86:70
info:
info:   http://localhost:xxxxx/components/bower_components/angular/angular.min.js:101
info: Error: undefined is not a function (evaluating 'a.state.targetUrl.startsWith("/client-detail")')
info: http://localhost:xxxxx/build/app.min.js:2:1501
info: http://localhost:xxxxx/components/bower_components/angular/angular.min.js:111:183
info: $eval@http://localhost:xxxxx/components/bower_components/angular/angular.min.js:125:40
info: $digest@http://localhost:xxxxx/components/bower_components/angular/angular.min.js:122:132
info: $apply@http://localhost:xxxxx/components/bower_components/angular/angular.min.js:125:314
info: m@http://localhost:xxxxx/components/bower_components/angular/angular.min.js:80:461
info: N@http://localhost:xxxxx/components/bower_components/angular/angular.min.js:85:33
info: onload@http://localhost:xxxxx/components/bower_components/angular/angular.min.js:86:70
info:
info:   http://localhost:xxxxx/components/bower_components/angular/angular.min.js:101
ERR on phantom create:
Error: Timeout wating for invoice page; max loops.
    at ...app/modules/client/invoice.js:147:19
    at process._tickCallback (internal/process/next_tick.js:103:7)
2017-08-31T18:20:01.008Z - error: ERROR (public,api). Timeout wating for invoice page; max loops. ip=63.225.154.15, method=GET, originalUrl=/api/invoice/59a8533654d75e127b8d6f8c, path=/invoice/59a8533654d75e127b8d6f8c, userId=xxxxx, req_id=94bbff619e196bc1ae295251ebc8a590b802b6f7, status=undefined, message=Timeout wating for invoice page; max loops., userMessage=undefined, stack=Error: Timeout wating for invoice page; max loops.
    at ...app/modules/client/invoice.js:147:19
    at process._tickCallback (internal/process/next_tick.js:103:7), status=undefined
```

**Comment by tonybranfort** [comment]
Another user: "That happens every now and then….usually you just exit out and reload and it works fine. "

**Comment by tonybranfort** [comment]
Because of `undefined is not a function (evaluating 'e.endsWith("/")')`, it seems to be due to issue that has been fixed in c0214e095e8a auth.service to replace endsWith with regEx for the comparison.   Should be resolved after upgrade to v2.0.  Closing.
